using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Database.Shared.Migrations
{
    /// <inheritdoc />
    public partial class EnsurePacientesInformacionExtra : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""PacientesInformacionExtra"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""PacienteId"" integer NOT NULL,
    ""AntecedentePersonalId"" integer NULL,
    ""Presento"" boolean NULL,
    ""Fecha"" timestamp with time zone NULL,
    ""Descripcion"" text NULL,
    ""Posicion"" integer NULL,
    ""Seccion"" integer NULL,
    ""Titulo"" text NULL,
    ""Nombre"" text NULL,
    ""Numero"" integer NULL,
    ""Variable1"" text NULL,
    ""Variable2"" text NULL,
    ""Variable3"" text NULL,
    ""Variable4"" text NULL,
    ""Base64"" text NULL,
    CONSTRAINT ""FK_PacientesInformacionExtra_Pacientes_PacienteId""
        FOREIGN KEY (""PacienteId"") REFERENCES ""Pacientes"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_PacientesInformacionExtra_AntecedentesPersonales_AntecedentePersonalId""
        FOREIGN KEY (""AntecedentePersonalId"") REFERENCES ""AntecedentesPersonales"" (""Id"")
);

CREATE INDEX IF NOT EXISTS ""IX_PacientesInformacionExtra_PacienteId""
    ON ""PacientesInformacionExtra"" (""PacienteId"");

CREATE INDEX IF NOT EXISTS ""IX_PacientesInformacionExtra_AntecedentePersonalId""
    ON ""PacientesInformacionExtra"" (""AntecedentePersonalId"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "PacientesInformacionExtra");
        }
    }
}
